### ISSUE TITLE
Keep on going...

### ISSUE THREAD

**Issue by AndreGuerra123** [insysbio/SbmlViewer#1]
You did an amazing job. Ty so much for this.
However I think that the best possible representation of model is probably a graph. 
Are you planning on developing a Vuejs  graph viewer/editor? I'm willing to collaborate on that. Which platforms do you recorrently use for viewing models? Are you planning to integrate this with Libsbml and analytical output tables?
Bets regards, AG. (ps: not really a issue just close it when answered)

**Comment by metelkin** [comment]
Thank you, @AndreGuerra123 
I agree that the graph representation would be informative and nice. We thought of it a lot. We have some experience (another internal project) in development application for graph visualization of metabolic systems in JavaScript experimenting with Cytoscape and JointJS. My current understanding is: to have nice and clear metabolic graph much work is required for rendering and elements visualization. It is not easy to do in the framework of SbmlViewer.

> Are you planning on developing a Vuejs graph viewer/editor?

It is not our priority but we have such plans for the future. Thank you for your help offer. We will let you know when we start.

> Which platforms do you recorrently use for viewing models?

Usually the visualization of models is not a critical part if you mean graph view. Simbiology can create more or less understandable diagram. The another model manipulation can be done in modeling software or SBML Editor application (Java).

> Are you planning to integrate this with Libsbml and analytical output tables?

There is no backend part in SbmlViewer. Libsbml cannot work in browser at all.
The philosophy of SbmlViewer is fast SBML transformation inside browser without uploading to server. To implement Libsbml and advanced analytics it is required to use another workflow. It will be totally another approach.
